CXX=g++ -g
LIBS=-llua5.1
RM=del /F
CFLAGS=-Wall -W -Wall -Wextra

.PHONY: all

all: test.exe

# Linking
test.exe: test.o ScriptedObject.o ScriptingContext.o
	$(CXX) $(CFLAGS) test.o ScriptedObject.o ScriptingContext.o -o $@ $(LIBS)

# Compile a .cpp into a .o
%.o: %.cpp
	$(CXX) -c $(CFLAGS) $< -o $@

# Clean up object files
clean:
	$(RM) *.o
